from watchtower.models import Title

TITLES: tuple[Title, ...] = (
    Title(
        id="aurora-drift",
        name="Aurora Drift",
        genre="Science Fiction",
        description="A salvage crew follows a signal beyond the mapped polar sky.",
        accent_from="#6E5AE6",
        accent_to="#22D3C5",
        baseline_popularity=1.28,
    ),
    Title(
        id="paper-moons",
        name="Paper Moons",
        genre="Drama",
        description="Three siblings rebuild a forgotten neighborhood observatory.",
        accent_from="#E78C5B",
        accent_to="#F4C96B",
        baseline_popularity=1.06,
    ),
    Title(
        id="quiet-frequency",
        name="The Quiet Frequency",
        genre="Mystery",
        description="A late-night radio host receives broadcasts from tomorrow.",
        accent_from="#315B83",
        accent_to="#8D78C4",
        baseline_popularity=1.18,
    ),
    Title(
        id="copper-tide",
        name="Copper Tide",
        genre="Adventure",
        description="Cartographers race a living coastline that redraws itself each dawn.",
        accent_from="#C66A3D",
        accent_to="#2B8D88",
        baseline_popularity=0.96,
    ),
    Title(
        id="orchard-nine",
        name="Orchard Nine",
        genre="Thriller",
        description="A botanist finds a coded warning inside an impossible harvest.",
        accent_from="#59763A",
        accent_to="#D6A64A",
        baseline_popularity=0.91,
    ),
    Title(
        id="glass-harbor",
        name="Glass Harbor",
        genre="Crime",
        description="A harbor archivist uncovers a city built on erased evidence.",
        accent_from="#487A93",
        accent_to="#A7D4D7",
        baseline_popularity=1.12,
    ),
    Title(
        id="after-the-static",
        name="After the Static",
        genre="Romance",
        description="Two sound engineers meet through recordings made years apart.",
        accent_from="#B9617D",
        accent_to="#5D65A8",
        baseline_popularity=0.88,
    ),
    Title(
        id="lantern-protocol",
        name="Lantern Protocol",
        genre="Techno-thriller",
        description="A safety engineer learns the city's emergency lights are voting.",
        accent_from="#E39B35",
        accent_to="#B84E3D",
        baseline_popularity=1.22,
    ),
    Title(
        id="small-hours-club",
        name="The Small Hours Club",
        genre="Comedy",
        description="Night-shift strangers turn a laundromat into an accidental newsroom.",
        accent_from="#4C96A8",
        accent_to="#E5B75D",
        baseline_popularity=0.82,
    ),
    Title(
        id="winter-index",
        name="The Winter Index",
        genre="Documentary Fiction",
        description="An archivist catalogs seasons that no longer arrive.",
        accent_from="#6E8EA4",
        accent_to="#DDE8E7",
        baseline_popularity=0.78,
    ),
    Title(
        id="violet-engine",
        name="Violet Engine",
        genre="Animation",
        description="A young mechanic repairs dreams in a city powered by color.",
        accent_from="#7F5BC7",
        accent_to="#E46FA8",
        baseline_popularity=1.01,
    ),
    Title(
        id="north-of-morning",
        name="North of Morning",
        genre="Family",
        description="A family maps a sunrise that keeps moving farther away.",
        accent_from="#4A82B8",
        accent_to="#F1B755",
        baseline_popularity=0.94,
    ),
)

TITLE_BY_ID = {title.id: title for title in TITLES}
REGIONS = ("North America", "Europe", "MENA", "South Asia", "Latin America")
CDN_NODES = {
    "North America": ("na-edge-01", "na-edge-02", "na-edge-03"),
    "Europe": ("eu-edge-01", "eu-edge-02", "eu-edge-03"),
    "MENA": ("me-edge-01", "me-edge-02", "me-edge-03"),
    "South Asia": ("sa-edge-01", "sa-edge-02", "sa-edge-03"),
    "Latin America": ("la-edge-01", "la-edge-02", "la-edge-03"),
}
